### ISSUE TITLE
all checks hanging

### ISSUE THREAD

**Issue by Zecke64** [agentless-monitoring/pywmi_wbem#11]
I wanted to use the tools from Ubuntu 20.04, monitoring a Windows Server2022 Std, domain member.
Upon starting any of the nagios checks it seems to run in a timeout and then prints "UNKNOWN: TypeError".
I tried with kerberos (preferred) and Basic Auth. Tried also with older Windows server versions, same story.
Any idea what could be wrong?

**Comment by davidvoit** [comment]
Please uncomment line 18 here https://github.com/agentless-monitoring/pywmi_wbem/blob/master/src/pywmi_wbem/wsman/query.py#L18

And try again. What is the output saying?

Basic Auth will not work without some settings before.
https://github.com/diyan/pywinrm#enabling-winrm-on-remote-host
But be careful, this is quite insecure for http only

**Comment by Zecke64** [comment]
root@icinga:/opt/icinga/pywmi_wbem# ./nagios_checks/check_disk_wbem -H back2015
UNKNOWN: GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): Matching credential not found (filename: /tmp/krb5cc_0)

root@icinga:/opt/icinga/pywmi_wbem# ls -l /tmp/krb5cc_0
-rw------- 1 root root 1.7K Mar  7 10:49 /tmp/krb5cc_0

root@icinga:/opt/icinga/pywmi_wbem# klist
Credentials cache: FILE:/tmp/krb5cc_0
        Principal: nagiosadmin@<mydomain>.DE
  Issued                Expires               Principal
Mar  7 10:49:17 2022  Mar  7 20:49:17 2022  krbtgt/<mydomain>.de@<mydomain>.DE

Using the same account (nagiosadmin) with wmic from Samba distribution is working.

**Comment by davidvoit** [comment]
You need to use a fqdn Form all Kerberos stuff,
else it will mit find the wsman spn

You are usung a Shortname only

Zecke64 ***@***.***> schrieb am Mo., 7. März 2022, 11:06:

**Comment by Zecke64** [comment]
Sorry, apparently the github edit window crippled sth. in my answer.
I used the Principal: nagiosadmin@mydomain.de in kinit.
I just tried also specifying the host as fqdn (back2015.mydomain.de) with no difference.

**Comment by davidvoit** [comment]
Please run:
1.) klist
2.) kvno WSMAN/back2015.mydomain.de

**Comment by Zecke64** [comment]
Hmm, I' installed Heimdal Kerberos it seems not to have a kvno. (klist see in my previous post).
Should I switch to MIT Kerberos? 
(Didn't know which one would be more appropriate)

**Comment by davidvoit** [comment]
We only tested mit Kerberos. I cant help you with heimdal stuff

Zecke64 ***@***.***> schrieb am Mo., 7. März 2022, 11:35:

**Comment by Zecke64** [comment]
Got it! Apparently it's necessary to use MIT Kerberos.
Great!
Thanks for your help.
